=== kohirens/tmpltoapp/template.schema.json
{
    "$comment": "see here for clarity: https://json-schema.org/understanding-json-schema/index.html",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/kohirens/tmplpress/blob/main/template.schema.json",
    "title": "Template Placeholder Manifest",
    "description": "Provide list a placeholder variables names for a template",
    "version": "2.2.0",
    "type": "object",
    "required": [ "version", "placeholders" ],
    "properties": {
        "version": {
            "description": "The semantic version of the template.json schema used",
            "type": "string",
            "pattern": "\\d\\.\\d(\\.\\d)?"
        },
        "placeholders": {
            "description": "A map where the keys are the placeholder names and the values are strings to present as a question to ask for the value in a CLI prompt",
            "type": "object"
        },
        "emptyDirFile": {
            "description": "Name of a file that marks a directory as empty and has the effect of \"mkdir -p\". This file allows you to add directories to Git but have them made and empty when the template is pressed.",
            "type": "string",
            "pattern": "^\\.?[a-zA-Z0-9-_.]+$"
        },
        "copyAsIs": {
            "description": "A list of files and directories to skip template processing and copy to the output directory unaltered.",
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "skip": {
            "description": "A list of files and directories to completely skip, will not be processed or copied to the output directory",
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "validation": {
            "description": "Validation for placeholder values.",
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "$ref": "#/$defs/validator"
            }
        },
        "substitute": {
            "description": "Name of a directory containing files to overwrite at the root of the template before template processing. This is for cases where you need to include files, for example, automation but also want one for the template.",
            "type": "string",
            "pattern": "^\\.?[a-zA-Z0-9-_.]+$"
        }
    },
    "$defs": {
        "validator": {
            "$anchor": "validator",
            "type": "object",
            "required": ["fields", "rule"],
            "properties": {
                "fields": {
                    "type": "array",
                    "minItems": 1
                },
                "rule": {
                    "type": "string",
                    "enum": ["alphaNumeric", "regExp"]
                },
                "expression": {
                    "type": "string",
                    "format": "regex"
                }
            },
            "dependentRequired": {
                "regExp": [ "expression" ]
            }
        }
    }
}

=== kohirens/tmpltoapp/subcommand/manifest/testdata/template-2.2.0-04.json
{
    "emptyDirFile": ".empty",
    "placeholders": {
        "var1": ""
    },
    "validation": [
        {
            "rule": "regExp",
            "fields": ["var1"],
            "expression": "[a-z",
            "message": "broken regexp will fail validation"
        }
    ],
    "version": "2.2.0"
}

=== kohirens/tmpltoapp/subcommand/manifest/testdata/template-2.2.0-03.json
{
    "emptyDirFile": ".empty",
    "placeholders": {
        "var1": ""
    },
    "validation": [
        {
            "rule": "regExp",
            "fields": ["var1"],
            "expression": "",
            "message": "empty regex will fail validation"
        }
    ],
    "version": "2.2.0"
}

=== kohirens/tmpltoapp/subcommand/manifest/testdata/template-2.2.0-02.json
{
    "emptyDirFile": ".empty",
    "placeholders": {
        "var1": ""
    },
    "validation": [
        {
            "rule": "alphaNumeric",
            "fields": ["var1", "var2"],
            "message": "human readable name with capitalization and spaces"
        }
    ],
    "version": "2.2.0"
}
